import React, { useEffect, useState } from 'react';
import authReference from './assets/auth-reference.jpeg';
import entryReference from './assets/entry-reference.jpeg';
import recordsReference from './assets/records-reference.jpeg';

const purple = 'from-[#4a3bc3] via-[#3026a7] to-[#24274b]';
const routes = ['welcome', 'mission', 'entry', 'phone', 'verify', 'password', 'dashboard', 'records', 'details'];
const patients = [
  ['Johnson Ebubechi', '28'], ['Favor Michael', '72'], ['Chukwumeka Chuks', '38'],
  ['Delight Nwanuko', '28'], ['Janet Iyangwa', '26'], ['Christian Ihenacho', '29'], ['Chidera Anita', '30'],
];

function KodaLogo({ small = false }) {
  return <div className={`text-center text-white ${small ? 'scale-75' : ''}`}>
    <svg className="mx-auto h-20 w-40 drop-shadow" viewBox="0 0 160 90" fill="none" aria-label="KODA care logo">
      <path d="M19 43 2 25l29 12-19-22 31 18M141 43l17-18-29 12 19-22-31 18M47 38c9 8 12 16 12 28M113 38c-9 8-12 16-12 28M65 27v31m-12-16h24M69 66l-9 12m31-12 9 12" stroke="white" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M80 18c8 0 14 6 14 14s-6 14-14 14-14-6-14-14 6-14 14-14Z" stroke="white" strokeWidth="4"/>
    </svg>
    <div className="-mt-2 text-[13px] tracking-[0.35em]">KODA</div>
    <div className="text-[10px] tracking-wider">care..........</div>
  </div>;
}

function TopBar() { return <header className="fixed inset-x-0 top-0 z-20 flex h-[92px] items-center bg-[#302f31] px-8 text-white shadow-sm"><span className="text-[35px] font-thin leading-none">☰</span><h1 className="absolute left-0 right-0 text-center font-sans text-[29px] font-normal">E-Hospital Application</h1></header>; }
function BottomBar() { return <div className="absolute bottom-0 flex h-8 w-full items-center justify-between rounded-b-xl bg-[#dedede] px-3 text-[17px] text-black"><span className="rounded border border-black px-1 text-[14px]">♧</span><span className="rounded-full bg-black px-1 text-[13px] text-white">i</span></div>; }
function Shell({ children, className = '', background }) { return <main className="min-h-screen bg-[#f5f5f5] pt-[170px] pb-14"><TopBar/><section className={`relative mx-auto h-[575px] w-[200px] overflow-hidden rounded-[11px] border border-[#777] shadow-sm ${className}`} style={background ? { backgroundImage: `url(${background})`, backgroundSize: '720px 1150px' } : undefined}>{children}</section></main>; }
function Next({ onClick, className = '' }) { return <button onClick={onClick} className={`rounded-2xl border border-[#bdb7d5] bg-[#d9d5e6] px-3 py-1 text-[12px] text-[#3a335e] shadow ${className}`}>NEXT</button>; }
function PersonIcon() { return <div className="grid h-12 w-12 place-items-center rounded-full border border-black bg-[#eee] text-[31px] leading-none text-black">♙</div>; }
function goTo(route) { window.location.hash = route; }

function Welcome() { return <Shell className="bg-[#8780d3] bg-cover bg-center" background={entryReference}><div className="absolute inset-0 bg-[#877fd5]/55"/><div className="relative pt-32"><KodaLogo/><button onClick={() => goTo('mission')} aria-label="Continue" className="absolute right-3 top-4 grid h-8 w-8 place-items-center rounded-full border border-white text-white">◌</button></div></Shell>; }
function Mission() { return <Shell background={entryReference} className="bg-cover bg-center"><div className="absolute inset-0 bg-black/10"/><div className="absolute left-[-18px] top-[195px] w-[235px] -rotate-[23deg] bg-[#dedede] py-3 text-center text-[10px] text-black">WE MAKE A DIFFERENCE</div><Next className="absolute bottom-1 left-2" onClick={() => goTo('entry')}/></Shell>; }
function Entry() { return <Shell background={entryReference} className="bg-cover bg-center"><div className="absolute inset-0 bg-[#6370db]/60"/><div className="relative flex h-full flex-col items-center pt-[235px] text-center text-white"><div className="w-36 text-[14px] font-bold leading-3 drop-shadow">DIGITIZE YOUR<br/>HEALTH TODAY</div><div className="mt-5 flex gap-3"><button onClick={() => goTo('dashboard')} className="w-20 rounded-xl border border-white py-2 text-[11px]">LOG IN</button><button onClick={() => goTo('phone')} className="w-20 rounded-xl border border-white py-2 text-[11px]">SIGN UP</button></div><p className="mt-4 w-40 text-left text-[13px] leading-3 text-[#233491]">An E-platform<br/>for better patient<br/>care.......</p></div><BottomBar/></Shell>; }
function AuthLayout({ children, photo = false }) { return <Shell background={photo ? authReference : undefined} className={`bg-gradient-to-b ${purple}`}><div className={photo ? 'absolute inset-0 bg-[#2c66ca]/55' : ''}/><div className="relative h-full">{children}<BottomBar/></div></Shell>; }
function Phone() { return <AuthLayout><div className="pt-11"><KodaLogo/></div><div className="px-7 pt-6 text-white"><h2 className="text-[13px] font-bold leading-3">INPUT YOUR PHONE<br/>NUMBER</h2><div className="mt-3 flex h-4 items-center gap-1 rounded-full border border-white px-1 text-[8px]"><span>🇳🇬</span><span className="rounded-full border border-white px-2">+234</span><span className="opacity-80">e.g 07067787689</span></div><p className="mt-1 text-[7px] text-[#f59595]">Phone number must be a total of 11 digits</p><Next className="float-right mt-3" onClick={() => goTo('verify')}/></div></AuthLayout>; }
function Verify() { return <AuthLayout photo><div className="pt-[135px] px-5 text-white"><h2 className="text-[13px] font-bold leading-3">INPUT VERIFICATION<br/>CODE</h2><div className="mt-4 flex justify-between">{['9','5','9','9'].map((number, i) => <div key={i} className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#263e5e] bg-[#deded5] text-[13px] text-[#252e3d]">{number}</div>)}</div><p className="mt-2 text-[7px]">Input verification code sent to the number above</p><Next className="float-right mt-3" onClick={() => goTo('password')}/></div></AuthLayout>; }
function Field({ label, placeholder, note }) { return <div className="mt-4"><label className="block text-[12px] font-bold leading-3 text-white">{label}</label><input aria-label={label} placeholder={placeholder} className="mt-2 h-4 w-full rounded-full border border-white bg-transparent px-3 text-[8px] text-white placeholder:text-[#d9d8e8]"/>{note && <p className="mt-1 text-[7px] leading-2 text-white">{note}</p>}</div>; }
function Password() { return <AuthLayout><div className="pt-8"><KodaLogo small/></div><div className="px-9"><Field label="INPUT AN 8-DIGIT PASSWORD" placeholder="e.g 457688932" note="Number must be a total of 8 or more digits"/><Field label="" placeholder="e.g 457688932" note="Confirm Password"/><Field label="INPUT YOUR FIRST NAME" placeholder="e.g Okonkwo"/><Field label="INPUT YOUR LAST NAME" placeholder="e.g Ejiedafor"/><Field label="OTHER NAMES ...IF ANY" placeholder=""/><Next className="float-right mt-4" onClick={() => goTo('dashboard')}/></div></AuthLayout>; }
function Dashboard() { const choices=[['✚','Bookings'],['▣','Patient\nRecords'],['●','Call triage'],['⌂','Location'],['♙','Need help?']]; return <Shell background={recordsReference} className="bg-cover bg-center"><div className="absolute inset-0 bg-[#e2edf0]/55"/><div className="relative pt-7 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full border border-white bg-white/30 text-[25px]">♙</div><div className="mx-auto mt-2 h-12 w-36 rounded-2xl border border-white/70"/><div className="mx-auto -mt-8 grid w-[178px] grid-cols-3 gap-2 pt-4">{choices.map(([icon,label], i)=><button key={label} onClick={() => label.includes('Patient') && goTo('records')} className={`grid h-12 place-items-center rounded-full border-2 border-white bg-[#103a68]/70 text-[8px] text-white ${i === 4 ? 'col-start-2' : ''}`}><span className="text-[20px] leading-3">{icon}</span><span className="whitespace-pre-line leading-2">{label}</span></button>)}</div><div className="mt-8"><KodaLogo small/></div></div><div className="absolute bottom-0 flex h-6 w-full justify-around bg-[#dedede] pt-1 text-[7px] text-black"><span>Contact us</span><span>Feedback</span><span>About us</span></div></Shell>; }
function Records() { return <Shell className={`bg-gradient-to-b ${purple}`}><div className="relative bg-white pt-5"><div className="flex h-6 items-center justify-between bg-[#3b2796] px-3 text-[11px] font-bold text-white"><span>Patient Records</span><span className="text-xl text-black">☰</span></div>{patients.map(([name,age]) => <button onClick={() => goTo('details')} key={name} className="flex h-[67px] w-full items-center border-b-2 border-[#372385] px-1 text-left text-[#49358e]"><div className="flex-1 text-[10px] leading-3"><b>{name}</b><br/>Age : {age}<p className="mt-2 font-bold">Click for more details</p></div><PersonIcon/></button>)}</div></Shell>; }
function Details() { return <Shell className={`bg-gradient-to-b ${purple}`}><div className="relative pt-5"><div className="h-6 bg-[#3b2796] px-3 pt-1 text-[11px] font-bold text-white">Patient Records</div><div className="m-1 min-h-[130px] bg-[#dfdfdc] p-2 text-[10px] leading-3 text-[#5a5193]"><div className="flex items-center justify-between"><div><b>Johnson Ebubechi</b><br/>Age : 28</div><PersonIcon/></div><div className="mt-2 border-t-2 border-[#372385] pt-3"><b>Health Status : <span className="text-yellow-300">Recovering</span></b><br/><b>Occupation : Architect</b><br/><b>Allergies : None</b><br/><b>Hospitals Visited : 3</b><br/><b>Appointments booked : 11/7/26</b></div></div><div className="m-1 h-32 bg-[#e0e0dd] p-1"><div className="flex gap-3"><div className="grid h-12 w-12 place-items-center rounded-full border border-black bg-[#f6ce14] text-[27px]">▣</div><div className="grid h-12 w-12 place-items-center rounded-full border border-black bg-[#f6ce14] text-[28px]">☝</div></div></div></div><BottomBar/></Shell>; }

export default function App() { const [route, setRoute] = useState((window.location.hash || '#welcome').slice(1)); useEffect(() => { const update = () => setRoute((window.location.hash || '#welcome').slice(1)); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []); const pages={welcome:<Welcome/>,mission:<Mission/>,entry:<Entry/>,phone:<Phone/>,verify:<Verify/>,password:<Password/>,dashboard:<Dashboard/>,records:<Records/>,details:<Details/>}; return pages[routes.includes(route) ? route : 'welcome']; }
